version: '3.8'

services:
  backend:
    image: sororiri/entto-backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5502:80
      - 4444:443
    env_file:
      - ./.env
    environment:
      - TYPEORM_HOST=host.docker.internal
      - PORT=80
      - HTTPS_PORT=443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt:ro
      - /home/sori/db/entto/:/app/uploads
    extra_hosts:
      host.docker.internal: host-gateway
