version: '3.8'

services:
  backend:
    image: sororiri/entto-backend:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5501:80
      - 4443:443
    env_file:
      - ./.env
    environment:
      - TYPEORM_HOST=host.docker.internal
      - PORT=80
      - HTTPS_PORT=443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt:ro
      # - ./uploads_/:/app/uploads_
    extra_hosts:
      host.docker.internal: host-gateway
