table users as u {
  id integer [pk, increment]
  username varchar(100) [not null]
  email varchar(100) [not null, unique]
  password varchar(100) [not null]
}

table companies as cp {
  id integer [pk, increment]
  company_name varchar(100) [not null]
}

table company_posts as cpp {
  id integer [pk, increment]
  companies_id integer [ref: > cp.id, not null]
  company_name varchar(100) [not null]
  level_2_categories_id integer [ref: > lv2_cate.id, not null]
  company_img_url varchar(100) [not null]
  company_short_desc varchar(100) [not null]
  homepage_url varchar(100)
  main_bussiness_tags varchar(300) [not null]
  company_long_desc varchar(1000)
  fastfive_benefit_desc varchar(100)
  company_contact_address varchar(100) [not null]
  company_info_url varchar(100)
  fastfive_branches_id integer [ref: > fb.id, not null]
  users_id integer [ref: - u.id, not null]
}

table company_post_forms as cpf {
  id integer [pk, increment]
  companies_id integer [ref: > cp.id, not null]
  company_name varchar(100)
  level_2_categories_id integer [ref: > lv2_cate.id]
  company_img_url varchar(100)
  company_short_desc varchar(100)
  homepage_url varchar(100)
  main_bussiness_tags varchar(300)
  company_long_desc varchar(1000)
  fastfive_benefit_desc varchar(100)
  company_contact_address varchar(100)
  company_info_url varchar(100)
  fastfive_branches_id integer [ref: > fb.id]
  updated_at "datetime default now() ON UPDATE now()" [not null]
  users_id integer [ref: - u.id]
}

table level_1_categories as lv1_cate {
  id integer [pk, increment]
  img_url varchar(500) [not null]
  category_name varchar(150) [not null, unique]
  description varchar(150)
}

table level_2_categories as lv2_cate {
  id integer [pk, increment]
  level_1_categories_id integer [ref: > lv1_cate.id]
  category_name varchar(150) [not null]
  description varchar(150)
}

table company_members as cpm {
  id integer [pk, increment]
  companies_id integer [ref: > cp.id]
  users_id integer [ref: - u.id]
  is_main_member tinyint [default: 0]
  Indexes {
    (companies_id, users_id) [unique]
  }
}

table fastfive_branches as fb {
  id integer [pk, increment]
  branch_name varchar(150) [not null]
  locations_id integer [ref: > locations.id]
}

table company_residences as cpr {
  companies_id integer [ref: - cp.id, pk]
  start_date datetime [not null]
  end_date datetime [not null]
  created_at "datetime default now()" [not null]
}

table comments as cmt {
  id integer [pk, increment]
  comments_id integer [ref: > cmt.id]
  users_id integer [ref: > u.id]
  company_posts_id integer [ref: > cpp.id]
  comment_content varchar(1000) [not null]
  is_secret tinyint [default: 0]
  depth integer
  sequence integer
  created_at "datetime default now()" [not null]
}

table banners as bn {
  id integer [pk, increment]
  banner_url varchar(200) [not null]
}

table locations {
  id integer [pk, increment]
  location_name varchar(100) [not null]
}

table admins as adm {
  users_id integer [ref: - u.id]
}

table company_request as mmr {
  id integer [pk, increment]
  users_id integer [ref: > u.id]
  company_name varchar(100) [not null]
  start_date datetime [not null]
  end_date datetime [not null]
}

table member_join_request as mjr {
  id integer [pk, increment]
  users_id integer [ref: > u.id]
  companies_id integer [ref: > cp.id]
  created_at "datetime default now()" [not null]
}